sudo: required
services: 
  - docker

before_install:
  - docker build -t basurohan/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run basurohan/client-test npm test -- --coverage

after_success:
  - docker build -t basurohan/multi-client ./client
  - docker build -t basurohan/multi-nginx ./nginx
  - docker build -t basurohan/multi-server ./server
  - docker build -t basurohan/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push basurohan/multi-client
  - docker push basurohan/multi-nginx
  - docker push basurohan/multi-server
  - docker push basurohan/multi-worker


